image: "ruby:2.6.3"
services:
  - postgres:latest

variables:
  POSTGRES_DB: test
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  RAILS_ENV: test
  LOGIN: xxx
  PASSWORD: xxx
  SECRET_TOKEN: 88e67b209fa6eb489b299e43e377e34d2e56840d

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - bundle install -j $(nproc) --path vendor

rspec:
  variables:
  script:
    - bundle exec rails db:migrate
    - bundle exec rspec spec

deploy:
  stage: deploy
  variables:
    HEROKU_APP_NAME: diguliu-octo
  dependencies:
    - rspec
  only:
    - master
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
